language: python

include:
  - os: linux
    sudo: true
    python: "3.5"
    dist: xenial

  - os: linux
    sudo: true
    python: 3.6
    dist: xenial

   - os: linux
    sudo: true
    python: 3.7
    dist: xenial

  - os: osx
    python: 3.5

  - os: osx
    python: 3.6

  - os: osx
    python: 3.7

# command to install dependencies
#before_install:
#  - sudo apt-get install coinor-cbc

install:
  - pip install .
  - pip install coveralls sphinx nbformat pytest-cov jupyter

# command to run tests
script:
  - coverage run --rcfile=.coveragerc --source windpowerlib -m py.test
  - coverage report

after_success:
  - coveralls


